### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by JeKuOrdina** [JeKuOrdina/SEBC#11]

**Comment by mfernest** [comment]
There is an error in your test job that leads to a major fault downstream. It appears you missed setting your block size correctly adding an extra zero. I added commas to highlight the issue:
```
...
-D dfs.block.size=640,000,000 \
...
```
As a result your job produced 16 blocks (each file is smaller than the maximum block size) instead of the expected amount 112:
```
Total blocks (validated):      16 (avg. block size 409600000 B)
```
This is the first time I've seen this parameter set incorrectly in the challenge. Without commas in machine output, it took me a moment to understand what had gone wrong. The consequence of course is that a subsequent validation test is incorrect. The number of splits computed for the terasort job in stage 5 is also incorrect (also this job runs quite a bit faster than expected).

For a stage to be complete, all the substantive exercises must have been submitted and must be error-free. I must mark this one as incomplete.
